# Generated by Django 5.2.1 on 2025-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.IntegerField()),
                ('tbl_comp_id', models.IntegerField(null=True)),
                ('comp_descripcion', models.CharField(max_length=250, null=True)),
                ('comp_tipo', models.CharField(max_length=50, null=True)),
                ('comp_nivel', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'TBL_COMPETENCIA',
            },
        ),
    ]
