# Generated by Django 5.2.1 on 2025-05-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_programa', '0002_tblcompetencia_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAprendizajePrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_aprendizaje', to='competencias_programa.competenciaprograma')),
            ],
        ),
        migrations.DeleteModel(
            name='TblCompetencia',
        ),
    ]
