# Generated by Django 5.2.1 on 2025-05-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_programa', '0003_competenciaprograma_resultadoaprendizajeprograma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competenciaprograma',
            name='nombre',
        ),
        migrations.AddField(
            model_name='competenciaprograma',
            name='id_programa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competenciaprograma',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(1, 'Básico'), (2, 'Medio'), (3, 'Avanzado')], default=1),
        ),
        migrations.AddField(
            model_name='resultadoaprendizajeprograma',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resultadoaprendizajeprograma',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_aprendizaje', to='competencias_programa.competenciaprograma'),
        ),
    ]
