# Generated by Django 5.2.1 on 2025-06-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubricas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(default='desconocido', max_length=255)),
                ('evaluador', models.CharField(default='desconocido', max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='rubricas.rubrica')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubricas.criterio')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluaciones.evaluacion')),
                ('nivel_seleccionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubricas.niveldesempeno')),
            ],
        ),
    ]
