# Generated by Django 5.2.1 on 2025-05-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0003_asignatura_competenciaasignatura_and_more'),
        ('competencias_programa', '0003_competenciaprograma_resultadoaprendizajeprograma_and_more'),
        ('evaluaciones', '0001_initial'),
        ('rubricas', '0003_criterio_nivel_rubrica_delete_resultaaprubrica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_evaluacion', to='rubricas.criterio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_evaluacion', to='rubricas.nivel')),
            ],
            options={
                'db_table': 'detalles_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('resultado_aprendizaje_asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignatura', to='competencias_asignatura.resultadoaprendizajeasignatura')),
                ('resultado_aprendizaje_programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_programa', to='competencias_programa.resultadoaprendizajeprograma')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='rubricas.rubrica')),
            ],
            options={
                'db_table': 'evaluaciones',
            },
        ),
        migrations.DeleteModel(
            name='EvaluacionPlaceholder',
        ),
        migrations.AddField(
            model_name='detalleevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='evaluaciones.evaluacion'),
        ),
    ]
