# Generated by Django 5.2.1 on 2025-05-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_detalleevaluacion_evaluacion_and_more'),
        ('rubricas', '0004_remove_nivel_valor_nivel_puntaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevaluacion',
            name='criterio',
        ),
        migrations.RemoveField(
            model_name='detalleevaluacion',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='detalleevaluacion',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='resultado_aprendizaje_asignatura',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='resultado_aprendizaje_programa',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='estudiante',
            field=models.CharField(default='desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='evaluador_id',
            field=models.CharField(default='desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='retroalimentacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='evaluacion',
            table=None,
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubricas.criterio')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluaciones.evaluacion')),
            ],
        ),
    ]
