# Generated by Django 5.2.1 on 2025-05-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_remove_detalleevaluacion_criterio_and_more'),
        ('rubricas', '0005_niveldesempeno_remove_rubrica_resultado_aprendizaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='nivel_seleccionado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubricas.niveldesempeno'),
        ),
        migrations.DeleteModel(
            name='DetalleEvaluacion',
        ),
    ]
