# Generated by Django 5.2.1 on 2025-05-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_resultadoevaluacion_nivel_seleccionado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='evaluador_id',
            new_name='evaluador',
        ),
    ]
