# Generated by Django 5.2.1 on 2025-06-05 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0001_initial'),
        ('competencias_programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciaasignatura',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_asignatura', to='competencias_programa.competenciaprograma'),
        ),
    ]
