# Generated by Django 5.2.1 on 2025-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asigcompdocente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblasignatura',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
