# Generated by Django 5.2.1 on 2025-06-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0002_competenciaasignatura_programa'),
        ('rubricas', '0003_remove_rubrica_resultado_aprendizaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciaasignatura',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_aprendizaje', to='rubricas.rubrica'),
        ),
    ]
