# Generated by Django 5.2.1 on 2025-05-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0002_asigcompdocente_activo_tblasignatura_activo'),
        ('competencias_programa', '0003_competenciaprograma_resultadoaprendizajeprograma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('creditos', models.PositiveIntegerField()),
                ('semestre', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='competencias_asignatura.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAprendizajeAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_aprendizaje', to='competencias_asignatura.competenciaasignatura')),
                ('relacionados_programa', models.ManyToManyField(blank=True, to='competencias_programa.resultadoaprendizajeprograma')),
            ],
        ),
        migrations.DeleteModel(
            name='AsigCompDocente',
        ),
        migrations.DeleteModel(
            name='TblAsignatura',
        ),
    ]
