# Generated by Django 5.2.1 on 2025-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0003_asignatura_competenciaasignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoaprendizajeasignatura',
            name='nombre',
            field=models.CharField(default='Nombre temporal', max_length=255),
        ),
    ]
