# Generated by Django 5.2.1 on 2025-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0004_resultadoaprendizajeasignatura_nombre'),
        ('competencias_programa', '0003_competenciaprograma_resultadoaprendizajeprograma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciaasignatura',
            name='competencias_programa',
            field=models.ManyToManyField(related_name='competencias_asignatura', to='competencias_programa.competenciaprograma'),
        ),
    ]
