# Generated by Django 5.2.1 on 2025-06-05 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0004_remove_competenciaasignatura_rubrica_and_more'),
        ('rubricas', '0004_alter_criterio_ponderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoaprendizajeasignatura',
            name='rubrica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado_aprendizaje', to='rubricas.rubrica'),
        ),
    ]
