# Generated by Django 5.2.1 on 2025-05-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0005_competenciaasignatura_competencias_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competenciaasignatura',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='competenciaasignatura',
            name='competencias_programa',
        ),
        migrations.RemoveField(
            model_name='competenciaasignatura',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='resultadoaprendizajeasignatura',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='resultadoaprendizajeasignatura',
            name='relacionados_programa',
        ),
        migrations.AddField(
            model_name='competenciaasignatura',
            name='id_asignatura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competenciaasignatura',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(1, 'Básico'), (2, 'Medio'), (3, 'Avanzado')], default=1),
        ),
        migrations.AddField(
            model_name='resultadoaprendizajeasignatura',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resultadoaprendizajeasignatura',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_aprendizaje', to='competencias_asignatura.competenciaasignatura'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
    ]
