# Generated by Django 5.2.1 on 2025-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblDocente',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_tipoidentificacion', models.CharField(max_length=50)),
                ('doc_tipodocente', models.CharField(max_length=50)),
                ('doc_nombres', models.CharField(max_length=100)),
                ('doc_apellidos', models.CharField(max_length=100)),
                ('doc_identificacion', models.CharField(max_length=100)),
                ('doc_titulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_DOCENTE',
            },
        ),
    ]
