# Generated by Django 5.2.1 on 2025-06-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(unique=True)),
                ('descripcion', models.CharField(default='Sin descripción', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ponderado', models.FloatField(default=1.0, help_text='Ponderación del criterio en la evaluación (0.0 a 1.0)')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Medio'), (3, 'Avanzado')], default=1)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='rubricas.rubrica')),
            ],
        ),
    ]
