# Generated by Django 5.2.1 on 2025-06-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0002_rubrica_resultado_aprendizaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='resultado_aprendizaje',
        ),
    ]
