# Generated by Django 5.2.1 on 2025-05-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias_asignatura', '0003_asignatura_competenciaasignatura_and_more'),
        ('rubricas', '0002_resultaaprubrica_activo_tblcriterio_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor', models.PositiveSmallIntegerField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='rubricas.criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='competencias_asignatura.resultadoaprendizajeasignatura')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultaapRubrica',
        ),
        migrations.DeleteModel(
            name='TblCriterio',
        ),
        migrations.DeleteModel(
            name='TblNivel',
        ),
        migrations.DeleteModel(
            name='TblRubrica',
        ),
        migrations.AddField(
            model_name='criterio',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='rubricas.rubrica'),
        ),
    ]
