# Generated by Django 5.2.1 on 2025-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0003_criterio_nivel_rubrica_delete_resultaaprubrica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='valor',
        ),
        migrations.AddField(
            model_name='nivel',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
