# Generated by Django 5.2.1 on 2025-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0003_remove_rubrica_resultado_aprendizaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='ponderado',
            field=models.FloatField(default=1.0),
        ),
    ]
