# Generated by Django 5.2.1 on 2025-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_remove_detalleevaluacion_criterio_and_more'),
        ('rubricas', '0004_remove_nivel_valor_nivel_puntaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')])),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='resultado_aprendizaje',
        ),
        migrations.AddField(
            model_name='criterio',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Medio'), (3, 'Avanzado')], default=1),
        ),
        migrations.AddField(
            model_name='criterio',
            name='ponderado',
            field=models.FloatField(default=1.0, help_text='Ponderación del criterio en la evaluación (0.0 a 1.0)'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
    ]
