# Generated by Django 5.2.1 on 2025-06-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0005_niveldesempeno_remove_rubrica_resultado_aprendizaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveldesempeno',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=100),
        ),
        migrations.AlterField(
            model_name='niveldesempeno',
            name='nivel',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
